playerObjectGUIDs = {
  White = {
    tray = 'ede27e',
    trayLiner = '05eab9',
    zone = '2a420b'
  },
  Red = {
    tray = 'c5ccf0',
    trayLiner = 'd4880b',
    zone = '968c8d'
  },
  Green = {
    tray = '8313d4',
    trayLiner = '382bd8',
    zone = '64c12e'
  },
  Blue = {
    tray = '34cb12',
    trayLiner = '435c47',
    zone = 'f2e70a'
  },
  Purple = {
    tray = '45461a',
    trayLiner = '933cba',
    zone = '7dc2c1'
  }
}
